### PR TITLE
Support for MacOS and AWS profiles

### PR DESCRIPTION
**Pull request by vpistis**
added support for macos, added option to select aws-cli credentials profile name, added some doc string, minor changes

### CODE REVIEW

**Comment by ze0adik** [comment]
Thank you for your interest in our tool and contribution. Please note that script imports all required modules with install_and_import() function. We will merge Mac OS and profile selection support soon.

**Comment by vpistis** [comment]
@ze0adik `install_and_import()` function is correctly used, I don't have installed other modules :)

**Comment by Volfar** [comment]
Could you clarify your comment? We just need to remove the third-party imports

**Comment by vpistis** [comment]
@Volfar sorry...the response was for the previous comment, and I forget that s3inspector is not an installable module :) ...you are right, I remove the explicit imports and push again

**Pull request merged**
